/*	Copyright 2013 by Martin Gijsen (www.DeAnalist.nl)
 *
 *	This file is part of the PowerTools.
 *
 *	The PowerTools are free software: you can redistribute them and/or
 *	modify them under the terms of the GNU Affero General Public License as
 *	published by the Free Software Foundation, either version 3 of the License,
 *	or (at your option) any later version.
 *
 *	The PowerTools are distributed in the hope that they will be useful,
 *	but WITHOUT ANY WARRANTY; without even the implied warranty of
 *	MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
 *	GNU Affero General Public License for more details.
 *
 *	You should have received a copy of the GNU Affero General Public License
 *	along with the PowerTools. If not, see <http://www.gnu.org/licenses/>.
 */

package org.powertools.graph;


public enum Colour {
	DEFAULT					("<default>"),
	TRANSPARENT				("transparent"),	

	ALICE_BLUE				("aliceblue"),
	ANTIQUE_WHITE			("antiquewhite"),
	AQUE					("aqua"),
	AQUAMARINE				("aquamarine"),
	AZURE					("azure"),
	BEIGE					("beige"),
	BISQUE					("bisque"),
	BLACK					("black"),
	BLANCHED_ALMOND			("blanchedalmond"),
	BLUE					("blue"),
	BLUE_VIOLET				("blueviolet"),
	BROWN					("brown"),
	BURLYWOOD				("burlywood"),
	CADET_BLUE				("cadetblue"),
	CHARTREUSE				("chartreuse"),
	CHOCALOATE				("chocolate"),
	CORAL					("coral"),
	CORNFLOWER_BLUW			("cornflowerblue"),
	CORNSILK				("cornsilk"),
	CRIMSON					("crimson"),
	CYAN					("cyan"),
	DARK_BLUE				("darkblue"),
	DARK_CYAN				("darkcyan"),
	DARK_GOLDENROD			("darkgoldenrod"),
	DARK_GRAY				("darkgray"),
	DARK_GREEN				("darkgreen"),
	DARK_GREY				("darkgrey"),
	DARK_KHAKI				("darkkhaki"),
	DARK_MAGENTA			("darkmagenta"),
	DARK_OLIVE_GREEN		("darkolivegreen"),
	DARK_ORANGE				("darkorange"),
	DARK_ORCHID				("darkorchid"),
	DARK_RED				("darkred"),
	DARK_SALMON				("darksalmon"),
	DARK_SEA_GREEN			("darkseagreen"),
	DARK_SLATE_BLUE			("darkslateblue"),
	DARK_SLATE_GRAY			("darkslategray"),
	DARK_SLATE_GREY			("darkslategrey"),
	DARK_TURQUOISE			("darkturquoise"),
	DARK_VIOLET				("darkviolet"),
	DEEP_PINK				("deeppink"),
	DEEP_SKY_BLUE			("deepskyblue"),
	DIM_GRAY				("dimgray"),
	DIM_GREY				("dimgrey"),
	DODGER_BLUE				("dodgerblue"),
	FIRE_BRICK				("firebrick"),
	FLORAL_WHITE			("floralwhite"),
	FOREST_GREEN			("forestgreen"),
	FUCHSIA					("fuchsia"),
	GAINSBORO				("gainsboro"),
	GHOST_WHITE				("ghostwhite"),
	GOLD					("gold"),
	GOLDENROD				("goldenrod"),
	GRAY					("gray"),
	GREY					("grey"),
	GREEN					("green"),
	GREEN_YELLOW			("greenyellow"),
	HONEYDEW				("honeydew"),
	HOT_PINK				("hotpink"),
	INDIAN_RED				("indianred"),
	INDIGO					("indigo"),
	IVORY					("ivory"),
	KHAKI					("khaki"),
	LAVENDER				("lavender"),
	LAVENDER_BLUSH			("lavenderblush"),
	LAWN_GREEN				("lawngreen"),
	LEMON_CHIFFON			("lemonchiffon"),
	LIGHT_BLUE				("lightblue"),
	LIGHT_CORAL				("lightcoral"),
	LIGHT_CYAN				("lightcyan"),
	LIGHT_GOLDENROD_YELLOW	("lightgoldenrodyellow"),
	LIGHT_GRAY				("lightgray"),
	LIGHT_GREEN				("lightgreen"),
	LIGHT_GREY				("lightgrey"),
	LIGHT_PINK				("lightpink"),
	LIGHT_SALMON			("lightsalmon"),
	LIGHT_SEA_GREEN			("lightseagreen"),
	LIGHT_SKY_BLUE			("lightskyblue"),
	LIGHT_SLATE_GRAY		("lightslategray"),
	LIGHT_SLATE_GREY		("lightslategrey"),
	LIGHT_STEEL_BLUE		("lightsteelblue"),
	LIGHT_YELLOW			("lightyellow"),
	LIME					("lime"),
	LIME_GREEN				("limegreen"),
	LINEN					("linen"),
	MAGENTA					("magenta"),
	MAROON					("maroon"),
	MEDIUM_AQUAMARINE		("mediumaquamarine"),
	MEDIUM_BLUE				("mediumblue"),
	MEDIUM_ORCHID			("mediumorchid"),
	MEDIUM_PURPLE			("mediumpurple"),
	MEDIUM_SEA_GREEN		("mediumseagreen"),
	MEDIUM_SLATE_BLUE		("mediumslateblue"),
	MEDIUM_SPRING_GREEN		("mediumspringgreen"),
	MEDIUM_TURQUOISE		("mediumturquoise"),
	MEDIUM_VIOLET_RED		("mediumvioletred"),
	MIDNIGHT_BLUE			("midnightblue"),
	MINT_CREAM				("mintcream"),
	MISTY_ROSE				("mistyrose"),
	MOCCASIN				("moccasin"),
	NAVAJO_WHITE			("navajowhite"),
	NAVY					("navy"),
	OLD_LACE				("oldlace"),
	OLIVE					("olive"),
	OLIVE_DRAB				("olivedrab"),
	ORANGE					("orange"),
	ORANGE_RED				("orangered"),
	ORCHID					("orchid"),
	PALE_GOLDENROD			("palegoldenrod"),
	PALE_GREEN				("palegreen"),
	PALE_TURQUOISE			("paleturquoise"),
	PALE_VIOLET_RED			("palevioletred"),
	PAPAYA_WHIP				("papayawhip"),
	PEACH_PUFF				("peachpuff"),
	PERU					("peru"),
	PINK					("pink"),
	PLUM					("plum"),
	POWDER_BLUE				("powderblue"),
	PURPLE					("purple"),
	RED						("red"),
	ROSY_BROWN				("rosybrown"),
	ROYAL_BLUE				("royalblue"),
	SADDLE_BROWN			("saddlebrown"),
	SALMON					("salmon"),
	SANDY_BROWN				("sandybrown"),
	SEA_GREEN				("seagreen"),
	SEA_SHELL				("seashell"),
	SIENNA					("sienna"),
	SILVER					("silver"),
	SKY_BLUE				("skyblue"),
	SLATE_BLUE				("slateblue"),
	SLATE_GRAY				("slategray"),
	SLATE_GREY				("slategrey"),
	SNOW					("snow"),
	SPRING_GREEN			("springgreen"),
	STEEL_BLUE				("steelblue"),
	TAN						("tan"),
	TEAL					("teal"),
	THISTLE					("thistle"),
	TOMATO					("tomato"),
	TURQUOISE				("turquoise"),
	VIOLET					("violet"),
	WHEAT					("wheat"),	
	WHITE					("white"),
	WHITE_SMOKE				("whitesmoke"),
	YELLOW					("yellow"),
	YELLOW_GREEN			("yellowgreen");
	
	private String text;

	private Colour (String text) {
		this.text = text;
	}

	@Override
	public String toString () {
		return this.text;
	}
}